# Generated by Django 5.2 on 2025-08-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='confirm_password',
        ),
    ]
