# Generated by Django 5.2 on 2025-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internapp', '0002_rename_email_reg_email_remove_reg_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_owner', models.CharField(max_length=30)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=100)),
                ('company_password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='reg',
            new_name='student',
        ),
    ]
