# Generated by Django 5.2 on 2025-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internapp', '0005_alter_internship_status_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
